site_name: Loquat
repo_name: Loquat
repo_url: https://github.com/Snownee/Loquat
site_author: Snownee
edit_uri: ""

nav:
  - "Preface": README.md
  - "Basic Area Operations": basic-area-operations.md
  - "Area Properties": area-properties.md
  - "Triggering Events": triggering-events.md
  - "Spawning Mobs": spawning-mobs.md
  - "Template Extension": template-extension.md
  - "Manipulating Jigsaws": manipulating-jigsaws.md
  - "Behind the Scenes": behind-the-scenes.md

theme:
  name: material
  language: en
  logo: images/site_icon.png
  favicon: images/site_icon.png
  features:
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.expand
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra_css:
  - stylesheets/extra.4c42df.css
extra_javascript:
  - path: scripts/extra.32b0df.js
    defer: false

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.progressbar
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search
  - awesome-pages