modLoader = "javafml"
loaderVersion = "[42,)"
license = "ARR"

[[mods]]
modId="loquat"
version="${file.jarVersion}"
displayName="Loquat"
authors="Snownee"
credits="SettingDust, zomb_676"
displayURL="https://www.curseforge.com/minecraft/mc-mods/loquat-forge"
description="Area management tool"
logoFile="logo.png"

[[dependencies.loquat]]
    modId="kiwi"
    mandatory=true
    versionRange="[11,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.loquat]]
    modId="lychee"
    mandatory=false
    versionRange="[5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.loquat]]
    modId="kubejs"
    mandatory=false
    versionRange="[2001.6,)"
    ordering="NONE"
    side="BOTH"

[modproperties.loquat]
    catalogueItemIcon="minecraft:jigsaw" #Support for Catalogue mod
